// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationMode } from "../CollaborationMode";
import type { Personality } from "../Personality";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { ServiceTier } from "../ServiceTier";
import type { WindowsSandboxLevel } from "../WindowsSandboxLevel";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ThreadTurnContextOverrideParams = { threadId: string, 
/**
 * Override the working directory for subsequent turns.
 */
cwd?: string | null, 
/**
 * Override the approval policy for subsequent turns.
 */
approvalPolicy?: AskForApproval | null, 
/**
 * Override where approval requests are routed for review on subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, 
/**
 * Override the sandbox policy for subsequent turns.
 */
sandboxPolicy?: SandboxPolicy | null, 
/**
 * Override the Windows sandbox level for subsequent turns.
 */
windowsSandboxLevel?: WindowsSandboxLevel | null, 
/**
 * Override the model provider for subsequent turns.
 */
modelProvider?: string | null, 
/**
 * Override the model for subsequent turns.
 */
model?: string | null, 
/**
 * Override the service tier for subsequent turns.
 */
serviceTier?: ServiceTier | null | null, 
/**
 * Override the reasoning effort for subsequent turns.
 */
effort?: ReasoningEffort | null, 
/**
 * Override the reasoning summary for subsequent turns.
 */
summary?: ReasoningSummary | null, 
/**
 * Override the personality for subsequent turns.
 */
personality?: Personality | null, 
/**
 * Override the collaboration mode for subsequent turns.
 */
collaborationMode?: CollaborationMode | null, };
